# Generated by Django 5.1.1 on 2025-03-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0002_rename_services_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="about",
            name="position",
            field=models.CharField(max_length=100),
        ),
    ]
