# Generated by Django 5.1.7 on 2025-03-12 06:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0005_service_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="experience",
            name="date",
        ),
        migrations.AddField(
            model_name="experience",
            name="end_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="experience",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
