# Generated by Django 5.1.7 on 2025-03-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0003_alter_about_name_alter_about_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="image",
            field=models.ImageField(default="images/default.jpg", upload_to="images"),
            preserve_default=False,
        ),
    ]
