# Generated by Django 5.1.7 on 2025-03-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0004_education_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="image",
            field=models.ImageField(default="images/default.jpg", upload_to="images"),
            preserve_default=False,
        ),
    ]
